// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PigeonUserDetails;

@interface PigeonUserDetails : NSObject
+ (instancetype)makeWithName:(nullable NSString *)name
    email:(nullable NSString *)email
    phone:(nullable NSString *)phone;
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * phone;
@end

/// The codec used by UserApi.
NSObject<FlutterMessageCodec> *UserApiGetCodec(void);

@protocol UserApi
/// @return `nil` only when `error != nil`.
- (nullable PigeonUserDetails *)getUserDetailsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)registerUserDetails:(PigeonUserDetails *)details error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpUserApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *_Nullable api);

NS_ASSUME_NONNULL_END
